# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
