# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('vegetables', '0002_vegetable_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart'),
        ),
    ]
