# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0004_remove_vegetable_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='subpricekg',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
