# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vegetables', '0004_remove_vegetable_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(choices=[('Basic', 'Basic'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=50)),
                ('cost', models.IntegerField()),
                ('moneyLeft', models.IntegerField()),
                ('dateStarted', models.DateTimeField(auto_now_add=True)),
                ('length', models.IntegerField()),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription_VegetableList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=3)),
                ('discount', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('veg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegetables.Vegetable')),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable_Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subuser', to='subscription.Subscription')),
                ('veglist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.Subscription_VegetableList')),
            ],
        ),
    ]
