# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegetableOrder', '0001_initial'),
        ('subscription', '0002_auto_20170421_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription_vegetablelist',
            name='veg',
        ),
        migrations.AddField(
            model_name='subscription_vegetablelist',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vegetableOrder.Vegetable_order'),
        ),
    ]
