# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20170419_1641'),
        ('vegetableOrder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetable_order',
            name='vegetable',
        ),
        migrations.AddField(
            model_name='vegetable_order',
            name='moneySaved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegetable_order',
            name='ordercart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart'),
        ),
    ]
