# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetableOrder', '0002_auto_20170421_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable_order',
            name='moneySaved',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vegetable_order',
            name='total',
            field=models.IntegerField(),
        ),
    ]
