# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20170419_1641'),
        ('vegetableOrder', '0003_auto_20170421_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetable_order',
            name='ordercart',
        ),
        migrations.AddField(
            model_name='vegetable_order',
            name='ordercart',
            field=models.ManyToManyField(blank=True, null=True, to='cart.Cart'),
        ),
    ]
