# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 06:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20170419_1641'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vegetableOrder', '0004_auto_20170422_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='vegetable_order_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ordercart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
            ],
        ),
        migrations.RemoveField(
            model_name='vegetable_order',
            name='ordercart',
        ),
    ]
