# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20170419_1641'),
        ('vegetableOrder', '0005_auto_20170422_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetable_order_list',
            name='order',
        ),
        migrations.RemoveField(
            model_name='vegetable_order_list',
            name='ordercart',
        ),
        migrations.AddField(
            model_name='vegetable_order',
            name='ordercart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart'),
        ),
        migrations.DeleteModel(
            name='vegetable_order_list',
        ),
    ]
