# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0005_vegetable_subpricekg'),
        ('vegetableOrder', '0006_auto_20170422_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetable_order',
            name='ordercart',
        ),
        migrations.AddField(
            model_name='vegetable_order',
            name='orderveg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vegetables.Vegetable'),
        ),
    ]
