# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0005_vegetable_subpricekg'),
        ('vegetableOrder', '0007_auto_20170422_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetable_order',
            name='orderveg',
        ),
        migrations.AddField(
            model_name='vegetable_order',
            name='orderveg',
            field=models.ManyToManyField(blank=True, null=True, to='vegetables.Vegetable'),
        ),
    ]
