# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 06:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vegetableOrder', '0008_auto_20170422_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable_order',
            name='orderdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 22, 6, 50, 16, 342094, tzinfo=utc)),
        ),
    ]
