# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 07:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vegetableOrder', '0010_auto_20170422_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable_order',
            name='orderdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 22, 7, 32, 50, 394524, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vegetable_order',
            name='quantity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
