# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vegetableOrder', '0011_auto_20170422_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable_order',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vegetable_order',
            name='orderdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 22, 8, 3, 39, 752126, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vegetable_order',
            name='quantity',
            field=models.CharField(max_length=200),
        ),
    ]
