# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 03:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vegetableOrder', '0013_auto_20170426_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable_order',
            name='orderdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 3, 38, 54, 512919, tzinfo=utc)),
        ),
    ]
